### ISSUE TITLE
Individual progress report not showing completed exercises/videos

### ISSUE THREAD

**Issue by jinchuika** [learningequality/ka-lite#4785]
- **Branch**: master (0.15.1)
- **Expected behavior**: when clicking on the blue button below the progress bar for exercises or videos, it should show what exercises are started or completed for that specific topic (see screenshot below).
- **Current behavior**: it shows a loading image and remains the same. The exercises and videos are not shown (see screenshot below).

### Steps to reproduce:
*Logged in as a learner*

1. Click on user name tab at the top-right corner
2. Go to My Progress
3. Click on the blue button below a progress bar

*Logged in as a teacher*

1. Go to Teach tab
2. Open the Tabular Report
3. Click on learner's name
4. Click on the blue button below a progress bar

**Expected behavior**  
![selection_002](https://cloud.githubusercontent.com/assets/5230176/12424329/42d81710-be95-11e5-96a0-06d423b96f30.png)

**Current behavior**
![bug](https://cloud.githubusercontent.com/assets/5230176/12424338/4f96069c-be95-11e5-8153-26d9f856b888.png)

## HOW IT CAN BE SOLVED (or avoided, at least)
This error occurred when I was installing the 0.15.1 version from both PPA and .deb file. But it didn't happened when I installed the 0.15.0 version and THEN updated to the 0.15.1 version.

**Comment by MCGallaspy** [comment]
@jinchuika thanks for the detailed report!

**Comment by MCGallaspy** [comment]
@rtibbles any thoughts on this?

**Comment by rtibbles** [comment]
Looks like it may be an error on the PlaylistDetailReport API endpoint, as the data is not fetching.

@jinchuika if you are able to get any information from the Javascript Console, that would also help!

**Comment by jinchuika** [comment]
Sorry @rtibbles, but I'm not able to get the info at the moment.  

However, I realized that running ```kalite manage setup``` to rebuild the database from the 0.15.1 version will also break the progress report.

**Comment by shubhsingh594** [comment]
hi all, 
Can i take this ?

**Comment by rtibbles** [comment]
@shubhsingh594 Yes - bear in mind, it is possible that this may work fine in English, but be problematic in another language, so test carefully!

**Comment by jinchuika** [comment]
Some other weird stuff I found:

1. If you create the database using `kalite manage setup` in version 0.15.0 and then upgrade to 0.15.1, it will be displayed, but only in English (like it was before #4650 was solved).
1. The previous point can be solved if you use `kalite restart` once the server has been started in that way, the report will be displayed using the translation.
1. Point No.2 only works with `kalite restart`, but it won't work using `kalite stop` and the `kalite start`.

**Comment by jinchuika** [comment]
I'm really sorry, but I miss-clicked and closed the issue.

**Comment by shubhsingh594** [comment]
@jinchuika hello,
 Can you open the javascript console, when the progress report is failing to show (after clicking on the blue button) and tell me if you are also seeing an error like this. 
SyntaxError: [sprintf] unexpected placeholder.

Because i checked and found out that PlaylistDetailReport API is sending a JSON reponse to the request, but it is not getting rendered.

**Comment by benjaoming** [comment]
@shubhsingh594 I've pulled in #4893 and rebuilt my assets, but the error ` SyntaxError: [sprintf] unexpected placeholder.` still occurs.

**Comment by benjaoming** [comment]
Forgive me, needed to run `collectstatic`, it works :)
