### ISSUE TITLE
Arabic not in Language dropdown

### ISSUE THREAD

**Issue by tim-moody** [learningequality/ka-lite#5266]
Summary
Arabic is no longer in the language selection dropdown

System information

Operating system: fedora 22
Version: 0.16.8
Browser: chrome

was able to install manually with kalite manage

**Comment by benridge** [comment]
I had the same issue.
Then I realized the [dashboard page](https://hub.learningequality.org/languages/dashboard) is showing the incorrect value for Arabic.
Dashboard shows 99% is translated, but the actual amount is 22%.
Not sure if it has reached the threshold for beta, but the interface definitely has translation issues, showing a mix of latin, cyrillic, chinese, and arabic characters in the learning menu (see attached screenshot) .
So the true bug is that the dashboard page is incorrectly calculating the amount translated.
Manually installing is the appropriate installation approach for a language that isn't yet beta.

<img width="564" alt="arabic language pack example" src="https://cloud.githubusercontent.com/assets/1683330/18236940/d5dc01fe-72e8-11e6-991b-10bba1c4a238.png">

**Comment by benjaoming** [comment]
@tim-moody @benridge thanks for reporting! It seems that the Arabic language packs aren't being built.

@aronasorman could you build and upload Arabic without rebuilding everything else?

The latest content pack zip is from 25-Mar-2016, which is way before we fixed a series of critical issues in the content packs.

**Comment by aronasorman** [comment]
@benjaoming Yup! Can add it. Although be warned that this bug seems to be happening in Khan Academy's side, due to their Arabic translations having erronous strings such as the ones you see here. So it's still not fixed with the latest content pack.

**Comment by aronasorman** [comment]
The best course of action here is to go to their Crowdin project ((www.crowdin.com/project/khanacademy)) and fix the strings there.

**Comment by benjaoming** [comment]
@aronasorman -- I guess the offical label of this content pack is "beta" still as in `"beta": true` ? :)

**Comment by benjaoming** [comment]
If you can build and upload just the `ar` language pack, it's fine... we can update the `all_metadata.json` manually...

**Comment by benjaoming** [comment]
@mrpau-eduard @mrpau-richard @cpauya - are you able to build the Arabic language pack?

**Comment by mrpau-richard** [comment]
Hi @benjaoming @benridge Here's the Arabic language pack [ar.zip](https://github.com/learningequality/ka-lite/files/505340/ar.zip)
I built it manually in my local, I will create a `PR` soon to build it at the build server.

**Comment by mrpau-richard** [comment]
@benridge & @benjaoming `Arabic` language pack contain only `ar` videos and the `strings` is not fully translated.

![screen shot 2016-10-03 at 9 17 22 am](https://cloud.githubusercontent.com/assets/8663934/19025343/3e52daec-894a-11e6-9028-2cdf04cf58c0.png)

![screen shot 2016-10-03 at 8 59 26 am](https://cloud.githubusercontent.com/assets/8663934/19025349/4a50c2e6-894a-11e6-865c-223f193989c4.png)

**Comment by benjaoming** [comment]
Nice @mrpau-richard!!

@benridge @tim-moody - would you be able to test the new contentpack? You can install it by running `kalite manage retrievecontentpack local ar path/to/ar.zip`

**Comment by tim-moody** [comment]
Finally got a chance to try the ar.zip link above.  This screen shot shows the result.

![image](https://cloud.githubusercontent.com/assets/5678731/19547557/d561e6b6-9666-11e6-80e4-c683c4e1de94.png)

**Comment by benjaoming** [comment]
@tim-moody that doesn't look super Arabic... looks like a bit of everything :)

@mrpau-richard could you have a look at why it seems that Russian (?) and perhaps Chinese is showing up, too?

**Comment by tim-moody** [comment]
This is basically what we had before; see my first screen shot.

is this the source https://ar.khanacademy.org/ ?

**Comment by tim-moody** [comment]
can someone explain the process for creating a language pack?

**Comment by benjaoming** [comment]
@tim-moody unfortunately the project is still internal.

https://github.com/fle-internal/content-pack-maker

@aronasorman anything that keeps us from moving it to a public realm?

**Comment by tim-moody** [comment]
I have a server headed for a school in Lebanon for Syrian refugee kids.  Sure would be nice to have this fixed.

**Comment by cpauya** [comment]
Hi @tim-moody - we're still in the process of testing our fixes for the French, Kiswahili, and Portuguese languages.  The French lang pack had a similar issue with yours which shows English along with translated stuff.  We hope to squeeze testing the Arabic language this week so we can give you feedback if it's also fixed.

**Comment by tim-moody** [comment]
Arabic has more speakers than any of those three according to
http://www.vistawide.com/languages/top_30_languages.htm

**Comment by mrpau-richard** [comment]
Hi @tim-moody & @benjaoming Now I found the issue, why is the Arabic content pack is not properly translated. It's because the [Khan academy translation](https://crowdin.com/project/khanacademy/ar), in Arabic has [0% translated string](https://crowdin.com/project/khanacademy/). I uploaded a sample `.pot` file from Khan academy translation is Arabic, but it's translated string is mixed with Chinese string.

Find the `數數` sting in the `.pot` file.
[learn.math.arithmetic-ar.po.zip](https://github.com/learningequality/ka-lite/files/578008/learn.math.arithmetic-ar.po.zip)

Here's the sample translated string logs when I build the Arabic content pack in my local.
![screen shot 2016-11-08 at 7 39 32 pm](https://cloud.githubusercontent.com/assets/8663934/20097834/69b5411c-a5eb-11e6-871a-90ec28418bb2.png)

I think we need to help translate or anyone knows about Arabic language in [khanacademy translation](https://crowdin.com/project/khanacademy/ar) to fix this issue.

**Comment by tim-moody** [comment]
Why does this problem not appear here?

https://ar.khanacademy.org/

**Comment by mrpau-richard** [comment]
@tim-moody The Arabic content pack will base its content in the [Khan academy Arabic api](http://www.khanacademy.org/api/v2/topics/topictree?lang=ar) if some video topics will not found it will use the  [Khan academy English api](http://www.khanacademy.org/api/v2/topics/topictree?lang=en). And the content pack maker will translate it using [Khan academy crowd in](https://crowdin.com/project/khanacademy/ar) translation.

**Comment by benridge** [comment]
As @tim-moody pointed out, the video are correctly titled and translated on https://ar.khanacademy.org. 

![image](https://cloud.githubusercontent.com/assets/1683330/20103943/27d4533a-a589-11e6-93a0-d8561c2c7ec8.png)

So it appears the online version is not using the Arabic content pack. 

The Arabic text is available in the online version, so what is needed to copy them into the Arabic content pack?

The online videos are the same as in KA-Lite, so the translations exist. It looks like something isn't setup correctly with the Arabic content pack and that this could be fixed without needing new translations as @mrpau-richard suggested.

**Comment by jamalex** [comment]
The text on https://ar.khanacademy.org/ is pulled directly from the titles of the playlists and videos on the KA Arabic YouTube channel. The translations used in the KA Lite topic tree come from KA's crowdin page. There's no direct mapping between playlists and topics in the topic tree, so it'd be hard to use those, but in principle we could look up the titles of each video in the YT API and use those as fallback titles in the language packs... Would take some work in the content pack maker.

**Comment by benjaoming** [comment]
Quick update: @mrpau-eduard and @mrpau-richard are going to have a look at updating the content packs w/ data via Youtube API.

We will also look at the possibility of syncing this data back into upstream CrowdIn.

After that, someone can look at translating remaining data, especially topic nodes (the nodes in the sidebar that don't have video or exercises). This can be done via CrowdIn.

@tim-moody @benridge are you Arabic speakers or do you know someone who would be able to do these additional translations through the CrowdIn interface?

**Comment by tim-moody** [comment]
As a temporary measure I have created a standalone module for Internet in a Box using ar.khanacademy.org and some javascript along the lines of KAOS.  Of course there are no exercises.  As a by-product I have a file with all the youtube ids (which I used to download them with youtube-dl).

Another problem for pulling this back into kalite is that at least some of the youtube ids for the ar.ka.org videos do not match the kalite AR language pack.

If you really get fancy, the whole topic tree is in the index.html file which could be parsed, but a non-Arabic speaker like myself is working in the dark.

**Comment by benridge** [comment]
Unfortunately I am not an Arabic speaker. I was working at a refugee camp and hoping to deploy KA Lite there but I have since returned home.  I don't have access to Arabic speakers any more.

**Comment by tim-moody** [comment]
@benridge I would be interested in speaking to you about your experiences with the refugee camp as I am working on a similar project.

**Comment by benjaoming** [comment]
Quick update here: We have decided to rebuild a lot of content packs and @mrpau-eduard has made an interface with Youtube for retrieving data such as titles and descriptions.

During next week we hope that an Arabic content pack will land for testing with the 0.17 prerelease, which will also become a final release not before long.

Please note that the user interface for KA Lite is only 23% translated: https://crowdin.com/project/ka-lite/ar

@aronasorman is creating a smaller update for the 0.17 translations, but they will largely be identical to 0.16.
